services:
  minio:
    image: cgr.dev/chainguard/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: MINIO_ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: MINIO_SECRET_ACCESS_KEY
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 MINIO_ACCESS_KEY_ID MINIO_SECRET_ACCESS_KEY &&
      mc mb --ignore-existing local/pev2-plans &&
      echo 'Bucket created'
      "

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PEV2_ON_S3_BUCKET_ENDPOINT: http://minio:9000
      PEV2_ON_S3_BUCKET_REGION: auto
      PEV2_ON_S3_BUCKET: pev2-plans
      PEV2_ON_S3_BUCKET_PATH_PREFIX: example
      PEV2_ON_S3_BUCKET_ACCESS_KEY_ID: MINIO_ACCESS_KEY_ID
      PEV2_ON_S3_BUCKET_SECRET_ACCESS_KEY: MINIO_SECRET_ACCESS_KEY
      PEV2_ON_S3_SERVER_PORT: "3000"
      PEV2_ON_S3_FRONTEND_SITE_TITLE: pev2.mysite.com
      PEV2_ON_S3_SHOW_EXAMPLES: "true"
    depends_on:
      minio-init:
        condition: service_completed_successfully

volumes:
  minio-data:
